### ISSUE TITLE
XSS/CSRF on term translator.

### ISSUE THREAD

**Issue by ehhthing** [leonzalion/website#4]
On the term translator, XSS is possible with the payload: `${alert(1)}` in "words to translate". This is because you use javascript's template literals, which allow for embedded code.

**Comment by leonzalion** [comment]
Thanks for pointing this out, I guess I didn't really think enough about my hack-ish way to get php interacting with javascript. I believe that I've fixed it by replacing all variables passed into $_POST that contain '${' with '\${', but if you can find another clever way to inject XSS/CSRF into the term translator, please do let me know ;)
